# Generated by Django 5.0.3 on 2024-04-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
