# Generated by Django 5.0.3 on 2024-04-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumcollection',
            options={'verbose_name': 'Коллекция музея', 'verbose_name_plural': 'Коллекции музеев'},
        ),
    ]
